const courses = [
    {
        id: 1,
        name: "French for begginers A1",
        description: "From daily greetings to basic expressions, learn French the simple & fun way! Start your journey today",
        Price: 150,
        image: "https://www.lawlessfrench.com/wp-content/uploads/french-for-beginners.png",
        rating: 4.5,
    },
    {
        id: 2,
        name: "Python from zero to hero",
        description: "learn Python like professinals with just 60 hours. Learn Python like a Professional Start from the basics and go all the way to creating your own applications and games",
        Price: 400,
        image: "https://cdn-media-0.freecodecamp.org/size/w2000/2021/12/chris-ried-ieic5Tq8YMk-unsplash.jpg",
        rating: 4.7,
    },
    {
        id: 3,
        name: "Diet And Nutrition Coach Certification",
        description: "Become A Nutrition Coach: Create Muscle Growth & Fat Loss Meal Plans, Build A Fitness Diet Business & Be A Health Expert",
        Price: 500,
        image: "https://www.mlchc.org/sites/default/files/styles/max_650x650/public/2022-03/nutrition_image2.jpg?itok=fUi0J40D",
        rating: 4.8,
    },
    {
        id: 4,
        name: "Data analyis for begginers",
        description: "Launch your career as a Power BI analyst. Build job-ready skills for an in-demand career in as little as 3 months. No prior experience required to get started.",
        Price: 700,
        image: "https://cdn.prod.website-files.com/605c9e03d6553a5d82976ce2/661d7f89ca4074cb868c6542_Screenshot%202024-04-16%20at%2012.54.52%20AM.png",
        rating: 4.7,
    },
    {
        id: 5,
        name: "Introduction to Healthcare Managment",
        description: "Become a transformative leader in healthcare. Explore how healthcare managers navigate the complexities of the healthcare system from both administrative and financial perspectives.",
        Price: 400,
        image: "https://i0.wp.com/iihmrdelhi.edu.in/blog/wp-content/uploads/2020/04/mba-hospital-management-iihmr.jpg?w=825&ssl=1",
        rating: 4.3,
    },
    {
        id: 6,
        name: "Javascript for begginers",
        description: "Learn how to use JavaScript — a powerful and flexible programming language for adding website interactivity.",
        Price: 200,
        image: "https://miro.medium.com/v2/resize:fit:720/format:webp/1*LyZcwuLWv2FArOumCxobpA.png",
        rating: 4.4,
    },
    {
        id: 7,
        name: "Principles for Digital Marketing",
        description: "Get on the fast track to a career in digital marketing. In this certificate program, you’ll learn in-demand skills, and get AI training from Google experts. Learn at your own pace, no degree or experience required.",
        Price: 200,
        image: "https://www.monash.edu/__data/assets/image/0006/3997950/illustration-digital-marketing.jpg",
        rating: 4.7,
    },
    {
        id: 8,
        name: "Business English Communication Skills Specialization",
        description: "Build English Skills for Business. Improve your ability to speak, write and understand English in professional settings.",
        Price: 300,
        image: "https://a.storyblok.com/f/236180/615b4868c5/how-to-improve-your-business-english-writing-skills-1.jpg",
        rating: 4.7,
    },
    {
        id: 9,
        name: "Introduction of First Aid",
        description: "A first aid training course equips individuals with the vital skills and confidence needed to handle medical emergencies. These programs typically cover essential topics such as CPR, treating wounds, and managing a variety of injuries and health conditions.",
        Price: 300,
        image: "https://www.aedcpr.com/images/online-cpr-aed-first-aid-class.webp",
        rating: 4.7,
    },
];
export default courses;